# Generated by Django 3.2.3 on 2021-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='minimum_bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
