# Generated by Django 3.2.3 on 2021-05-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='ye', max_length=45),
            preserve_default=False,
        ),
    ]
