# Generated by Django 3.2.3 on 2021-05-28 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 5, 28, 19, 7, 52, 836942))),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=9, null=True)),
            ],
        ),
    ]
