# Generated by Django 3.2.3 on 2021-05-26 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_rename_user_bid_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 5, 26, 14, 59, 5, 628286)),
        ),
    ]
