# Generated by Django 3.2.3 on 2021-05-28 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0015_auto_20210526_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 5, 28, 12, 51, 52, 803090)),
        ),
    ]
